#! /bin/sh

#pgrep -x sxhkd > /dev/null || sxhkd &
sxhkd &

if [[ $(xrandr -q | grep 'HDMI-1 connected') ]]; then
xrandr --output HDMI-1 --primary --mode 1920x1080 --rotate normal --output LVDS-1 --off
fi

nm-applet &
greenclip daemon &
$HOME/.config/polybar/launch.sh
feh --bg-fill /usr/share/backgrounds/bspwm/wall.png
picom &

#bspc monitor -d I II III IV V VI VII VIII IX X
if [[ $(xrandr -q | grep 'HDMI-1 connected') ]]; then
bspc monitor HDMI-1 -d I II III IV V
else
bspc monitor -d I II III IV V
fi

bspc config border_width         0
bspc config window_gap          0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a firefox desktop='^5'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a flameshot state='floating'

